# Header
menu:
  主页: /
  归档: /archives
  收集: /collect
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
#- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
